typography_spectrum: 0.3819919906090945
color:
  brandStrength: 0.2258426216430962
  lightness: 0.7535785872023553
  saturation: 0.9392686730716377
  rhythmicContrast: 0.9706435243133456
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.07775962981395423
author:
  name: Simon Laumet
  email: hello@simonlaumet.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b887e35e-149d-4fdd-9b4a-9a6018c19907.png
name: SL Industrial Design
title: SL Industrial Design
description: "Tech \_| \_Sport \_| \_Lifestyle"
