layout_spectrum: 0.6526041608303785
typography_spectrum: 0.6872339763212949
color:
  brandStrength: 0.017849080497398973
  lightness: 0.6433131177909672
  saturation: 0.8940619416534901
  rhythmicContrast: 0.046823927434161305
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
author:
  name: Simon Laumet
  email: hello@simonlaumet.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b887e35e-149d-4fdd-9b4a-9a6018c19907.png
name: SL Industrial Design
title: SL Industrial Design
description: "Tech \_| \_Sport \_| \_Lifestyle"
